name: release

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build release artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
        - build: linux
          os: ubuntu-latest
          cpu: x86_64
          rust: stable
          binary: dply
        - build: linux-20.04
          os: ubuntu-20.04
          cpu: x86_64
          rust: stable
          binary: dply
        - build: macos
          os: macos-latest
          cpu: x86_64
          rust: stable
          binary: dply
        - build: windows
          os: windows-latest
          cpu: x86_64
          rust: stable
          binary: dply.exe
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Run build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: dply-${{ inputs.version }}-${{ matrix.cpu }}-${{ matrix.os }}
        path: |
          target/release/${{ matrix.binary }}
